# Generated by Django 3.0.3 on 2020-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
