# Generated by Django 3.0.3 on 2020-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subject_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
