# Generated by Django 3.0.3 on 2020-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200417_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
